server:
  port: 8004

spring:
  application:
    name: exmall-cart
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host: common-redis-dev.magestack.cn
      port: 19389
      password: "Sm9sVXBOYJjI030b5tz0trjpzvZzRhtZmEbv0uOImcD1wEDOPfeaqNU4PxHob/Wp"
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

